FROM --platform=linux/amd64 golang:1.22-alpine as builder
WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download
COPY cmd ./cmd
COPY internal ./internal
RUN go build -o main cmd/app/main.go

FROM --platform=linux/amd64 alpine:3.19
COPY --from=builder /build/main /app/main
RUN chmod +x ./app/main
ENTRYPOINT ["/app/main"]
