FROM node:20.12-alpine AS build
WORKDIR /build
COPY webui/package.json webui/package-lock.json ./
RUN npm install
COPY webui/ .
RUN npm run ng build

FROM nginx:1.25.4-alpine
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /build/dist/webui/browser /usr/share/nginx/html
